# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: perkzen
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: faas
service: car-management-system

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    CARS_TABLE: ${self:service}-events
    JWT_SECRET: secret

plugins:
  - serverless-offline
  - serverless-localstack

custom:
  localstack:
    stages:
      - local

functions:
  login:
    handler: handler.login
    events:
      - http:
          path: /login
          method: post
          cors: true

  createCar:
    handler: handler.createCar
    events:
      - http:
          path: /cars
          method: post
          cors: true

  getCars:
    handler: handler.getCars
    events:
      - http:
          path: /cars
          method: get
          cors: true

  getCarById:
    handler: handler.getCarById
    events:
      - http:
          path: /cars/{id}
          method: get
          cors: true

  updateCar:
    handler: handler.updateCar
    events:
      - http:
          path: /cars/{id}
          method: put
          cors: true

  deleteCar:
    handler: handler.deleteCar
    events:
      - http:
          path: /cars/{id}
          method: delete
          cors: true

  scheduledTask:
    handler: handler.scheduledTask
    events:
      - schedule:
          rate: rate(5 minutes)


  processCarChanges:
    handler: handler.processCarChanges
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - CarsTable
              - StreamArn

  handleSnsNotification:
    handler: handler.handleSnsNotification
    events:
      - sns: carNotification

  handleUserLogin:
    handler: handler.handleUserLogin

resources:
  Resources:
    CarsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CARS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    EventNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: carNotification